name: Create Release

on:
  repository_dispatch:
    types: [create-release]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Extract version and setup release branch
        id: version
        run: |
          TITLE="${{ github.event.client_payload.pr_title }}"
          VERSION=$(echo "$TITLE" | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.-]+)?')
          MAJOR=$(echo "$VERSION" | cut -d. -f1 | sed 's/v//')
          MINOR=$(echo "$VERSION" | cut -d. -f2)
          RELEASE_BRANCH="release-$MAJOR.$MINOR"

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "release_branch=$RELEASE_BRANCH" >> $GITHUB_OUTPUT

          # Create or checkout release branch (persistent across patch releases)
          if ! git show-ref --verify --quiet refs/remotes/origin/"$RELEASE_BRANCH"; then
            echo "Creating new release branch $RELEASE_BRANCH"
            git checkout -b "$RELEASE_BRANCH"
            git push -u origin "$RELEASE_BRANCH"
          else
            echo "Checking out existing release branch $RELEASE_BRANCH"
            git checkout "$RELEASE_BRANCH"
          fi

      - name: Cherry-pick version commit
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          # Find the actual commit (not merge commit) with exact subject line
          COMMIT_SHA=$(git log --format="%H %s" "origin/${{ github.event.client_payload.pr_base_ref }}" | grep "^[a-f0-9]\{40\} Prepare release $VERSION$" | head -1 | cut -d' ' -f1)
          echo "Cherry-picking version commit $COMMIT_SHA"

          # Check if this version is already in version.json on the release branch
          CURRENT_VERSION=$(jq -r '.version' version.json)
          if [[ "$CURRENT_VERSION" == "$VERSION" ]]; then
            echo "Version $VERSION is already present on release branch, skipping cherry-pick"
          else
            # Cherry-pick using 'theirs' strategy to resolve conflicts by taking the new version
            git cherry-pick --strategy-option theirs "$COMMIT_SHA"
          fi

          git push origin "${{ steps.version.outputs.release_branch }}"

      - name: Create and sign release artifacts
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          make create-artifacts VERSION="$VERSION"
          make sign VERSION="$VERSION"

      - name: Create signed tag and draft release
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          VERSION="${{ steps.version.outputs.version }}"

          # Create annotated tag
          git tag --annotate "$VERSION" --message "Release $VERSION"
          git push origin "$VERSION"

          # Create draft release with artifacts
          if [[ "$VERSION" == *"-"* ]]; then
            gh release create "$VERSION" \
              --title "$VERSION" \
              --notes "Release $VERSION - Draft for review" \
              --draft \
              --prerelease \
              _dist/app-$VERSION-*
          else
            gh release create "$VERSION" \
              --title "$VERSION" \
              --notes "Release $VERSION - Draft for review" \
              --draft \
              _dist/app-$VERSION-*
          fi

      # Note: Docs update is triggered automatically when release is published via webhook
      # This ensures human review of draft release before docs automation begins
