name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v3.2.0)'
        required: true
        type: string

jobs:
  prepare:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Determine base and release branches
        id: branches
        run: |
          VERSION="${{ inputs.version }}"
          MAJOR=$(echo "$VERSION" | cut -d. -f1 | sed 's/v//')
          MINOR=$(echo "$VERSION" | cut -d. -f2)
          RELEASE_BRANCH="release-$MAJOR.$MINOR"

          if [ "$MAJOR" = "3" ]; then
            BASE_BRANCH="dev-v3"
          else
            BASE_BRANCH="main"
          fi

          echo "base_branch=$BASE_BRANCH" >> $GITHUB_OUTPUT
          echo "release_branch=$RELEASE_BRANCH" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create or checkout release branch
        run: |
          VERSION="${{ inputs.version }}"
          RELEASE_BRANCH="${{ steps.branches.outputs.release_branch }}"
          BASE_BRANCH="${{ steps.branches.outputs.base_branch }}"
          TEMP_BRANCH="prepare-$VERSION"

          # Create or checkout release branch (persistent across patch releases)
          if ! git show-ref --verify --quiet refs/remotes/origin/"$RELEASE_BRANCH"; then
            echo "Creating new release branch $RELEASE_BRANCH from $BASE_BRANCH"
            git checkout -b "$RELEASE_BRANCH" origin/"$BASE_BRANCH"
            git push -u origin "$RELEASE_BRANCH"
          else
            echo "Checking out existing release branch $RELEASE_BRANCH"
            git checkout "$RELEASE_BRANCH"
          fi

          # Create temporary preparation branch from release branch
          git checkout -b "$TEMP_BRANCH"
          echo "branch=$TEMP_BRANCH" >> $GITHUB_ENV

      - name: Update version
        run: |
          VERSION="${{ inputs.version }}"
          # Extract MAJOR.MINOR (e.g., v4.0.1 -> v4.0)
          MAJOR_MINOR=$(echo "$VERSION" | sed 's/^\(v[0-9]*\.[0-9]*\).*/\1/')
          jq --arg version "$MAJOR_MINOR" '.version = $version' version.json > version.json.tmp
          mv version.json.tmp version.json
          echo "Version updated to $MAJOR_MINOR (extracted from $VERSION)"

      - name: Commit and push
        run: |
          git add .
          git commit -s -m "Prepare release ${{ inputs.version }}"
          git push origin "${{ env.branch }}"

      - name: Create PR
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          gh pr create \
            --title "Prepare release ${{ inputs.version }}" \
            --body "Automated release preparation for ${{ inputs.version }}" \
            --base ${{ steps.branches.outputs.release_branch }} \
            --head "${{ env.branch }}"
