name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v3.2.0)'
        required: true
        type: string

jobs:
  prepare:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Determine base branch
        id: base
        run: |
          VERSION="${{ inputs.version }}"
          MAJOR=$(echo "$VERSION" | cut -d. -f1 | sed 's/v//')

          if [ "$MAJOR" = "3" ]; then
            BASE_BRANCH="dev-v3"
          else
            BASE_BRANCH="main"
          fi

          echo "base_branch=$BASE_BRANCH" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.base.outputs.base_branch }}

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create release branch
        run: |
          BRANCH="release-${{ inputs.version }}"
          git checkout -b "$BRANCH"
          echo "branch=$BRANCH" >> $GITHUB_ENV

      - name: Update version
        run: ./scripts/update-version.sh "${{ inputs.version }}"

      - name: Commit and push
        run: |
          git add .
          git commit -s -m "Prepare release ${{ inputs.version }}"
          git push origin "${{ env.branch }}"

      - name: Create PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create \
            --title "Prepare release ${{ inputs.version }}" \
            --body "Automated release preparation for ${{ inputs.version }}" \
            --base ${{ steps.base.outputs.base_branch }} \
            --head "${{ env.branch }}"
