name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v3.2.0)'
        required: true
        type: string

jobs:
  prepare:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Determine base and release branches
        id: branches
        run: |
          VERSION="${{ inputs.version }}"
          MAJOR=$(echo "$VERSION" | cut -d. -f1 | sed 's/v//')
          MINOR=$(echo "$VERSION" | cut -d. -f2)
          RELEASE_BRANCH="release-$MAJOR.$MINOR"

          if [ "$MAJOR" = "3" ]; then
            BASE_BRANCH="dev-v3"
          else
            BASE_BRANCH="main"
          fi

          echo "base_branch=$BASE_BRANCH" >> $GITHUB_OUTPUT
          echo "release_branch=$RELEASE_BRANCH" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create or checkout release branch and update version
        run: |
          VERSION="${{ inputs.version }}"
          RELEASE_BRANCH="${{ steps.branches.outputs.release_branch }}"
          BASE_BRANCH="${{ steps.branches.outputs.base_branch }}"

          # Create or checkout release branch (persistent across patch releases)
          if ! git show-ref --verify --quiet refs/remotes/origin/"$RELEASE_BRANCH"; then
            echo "Creating new release branch $RELEASE_BRANCH from $BASE_BRANCH"
            git checkout -b "$RELEASE_BRANCH" origin/"$BASE_BRANCH"
            git push -u origin "$RELEASE_BRANCH"
          else
            echo "Checking out existing release branch $RELEASE_BRANCH"
            git checkout "$RELEASE_BRANCH"
          fi

          # Update version.json if this is the first release in the series
          MAJOR_MINOR=$(echo "$VERSION" | sed 's/^\(v[0-9]*\.[0-9]*\).*/\1/')
          CURRENT_VERSION=$(jq -r '.version' version.json 2>/dev/null || echo "")

          if [[ "$CURRENT_VERSION" != "$MAJOR_MINOR" ]]; then
            echo "Updating version.json to $MAJOR_MINOR"
            jq --arg version "$MAJOR_MINOR" '.version = $version' version.json > version.json.tmp
            mv version.json.tmp version.json
            git add version.json
            git commit -s -m "Prepare release $VERSION"
            git push origin "$RELEASE_BRANCH"
            echo "Version updated and committed to release branch"
          else
            echo "Version $MAJOR_MINOR already present in release branch"
          fi

      - name: Trigger release workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          repository: ${{ github.repository }}
          event-type: create-release
          client-payload: |
            {
              "version": "${{ inputs.version }}",
              "release_branch": "${{ steps.branches.outputs.release_branch }}",
              "base_branch": "${{ steps.branches.outputs.base_branch }}"
            }
