name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v3.2.0, v4.0.1)'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Determine base and release branches
        id: branches
        run: |
          VERSION="${{ inputs.version }}"
          MAJOR=$(echo "$VERSION" | cut -d. -f1 | sed 's/v//')
          MINOR=$(echo "$VERSION" | cut -d. -f2)
          RELEASE_BRANCH="release-$MAJOR.$MINOR"

          if [ "$MAJOR" = "3" ]; then
            BASE_BRANCH="dev-v3"
          else
            BASE_BRANCH="main"
          fi

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "base_branch=$BASE_BRANCH" >> $GITHUB_OUTPUT
          echo "release_branch=$RELEASE_BRANCH" >> $GITHUB_OUTPUT

      - name: Setup release branch and update versions
        run: |
          VERSION="${{ steps.branches.outputs.version }}"
          RELEASE_BRANCH="${{ steps.branches.outputs.release_branch }}"
          BASE_BRANCH="${{ steps.branches.outputs.base_branch }}"

          # Function to update version.json
          update_version() {
            local branch="$1"
            local version="$2"
            local major_minor=$(echo "$version" | sed 's/^\(v[0-9]*\.[0-9]*\).*/\1/')
            local current_version=$(jq -r '.version' version.json 2>/dev/null || echo "")

            if [[ "$current_version" != "$major_minor" ]]; then
              echo "Updating version.json in $branch to $major_minor"
              jq --arg version "$major_minor" '.version = $version' version.json > version.json.tmp
              mv version.json.tmp version.json
              git add version.json
              git commit -s -m "Prepare release $version"
              git push origin "$branch"
              return 0
            else
              echo "Version $major_minor already present in $branch"
              return 1
            fi
          }

          # Create or checkout release branch
          if ! git show-ref --verify --quiet refs/remotes/origin/"$RELEASE_BRANCH"; then
            echo "Creating new release branch $RELEASE_BRANCH from $BASE_BRANCH"
            git checkout -b "$RELEASE_BRANCH" origin/"$BASE_BRANCH"
            git push -u origin "$RELEASE_BRANCH"
          else
            echo "Checking out existing release branch $RELEASE_BRANCH"
            git checkout "$RELEASE_BRANCH"
          fi

          # Update version on release branch
          update_version "$RELEASE_BRANCH" "$VERSION"

          # Update version on source branch
          echo "Updating source branch $BASE_BRANCH"
          git checkout "$BASE_BRANCH"
          git pull origin "$BASE_BRANCH"
          update_version "$BASE_BRANCH" "$VERSION"

          # Switch back to release branch for artifact creation
          git checkout "$RELEASE_BRANCH"


      - name: Create and sign release artifacts
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          VERSION="${{ steps.branches.outputs.version }}"
          make create-artifacts VERSION="$VERSION"
          make sign VERSION="$VERSION"

      - name: Create signed tag and draft release
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          VERSION="${{ steps.branches.outputs.version }}"

          # Create annotated tag
          git tag --annotate "$VERSION" --message "Release $VERSION"
          git push origin "$VERSION"

          # Create draft release with artifacts
          if [[ "$VERSION" == *"-"* ]]; then
            gh release create "$VERSION" \
              --title "$VERSION" \
              --notes "Release $VERSION - Draft for review" \
              --draft \
              --prerelease \
              _dist/app-$VERSION-*
          else
            gh release create "$VERSION" \
              --title "$VERSION" \
              --notes "Release $VERSION - Draft for review" \
              --draft \
              _dist/app-$VERSION-*
          fi

      # Note: Docs update is triggered automatically when release is published via webhook
      # This ensures human review of draft release before docs automation begins
